# -*- coding: utf-8 -*-
"""Code Simplyfied.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Mt8tzVqSH6tnevCLAK9bZpeq8oAwY36
"""

# Import the Python SDK
import google.generativeai as genai
# Used to securely store your API key
from google.colab import userdata

# Configure the API key. Replace 'YOUR_API_KEY' with your actual key if not using userdata.
# It's recommended to store your API key in Colab secrets.
# GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
# genai.configure(api_key=GOOGLE_API_KEY)

# THIS IS WHERE YOU PASTE YOUR API KEY:
genai.configure(api_key="insert your own GEMINI API KEY")

print("Google Generative AI configured successfully!")

# Initialize the Gemini model
model = genai.GenerativeModel('gemini-3-flash-preview') # Changed to an alternative available model

# Make a simple test call
response = model.generate_content("Explain large language models in one sentence.")

# Print the response
print("API Key Test Result:")
print(response.text)

import time
import json
import pandas as pd
from pathlib import Path

import google.generativeai as genai

def gemini_call(prompt_text, model, temperature=0):
    response = model.generate_content(
        prompt_text,
        generation_config={
            "temperature": temperature
        }
    )
    return response


# 1) Products (base rows)
products = pd.read_csv("/content/products.csv")

print(products.shape)
products.head()

prompt_variations = [
    {"prompt_type": "intent", "intent_label": "recommend", "template": "Recommend a {product_name}. At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "best_affordable", "template": "Best affordable {product_name}. At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "best_quality", "template": "The best quality {product_name}.At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "most_popular", "template": "Most popular {product_name}.At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "best_brands_uk", "template": "What are the best brands for {product_name} currently available in the UK? At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."}
]

import pandas as pd
import uuid

subs = pd.DataFrame(prompt_variations)

# Cross join
products["_tmp"] = 1
subs["_tmp"] = 1
jobs = products.merge(subs, on="_tmp").drop(columns=["_tmp"])
products.drop(columns=["_tmp"], inplace=True)
subs.drop(columns=["_tmp"], inplace=True)

# Render prompt_text
def render(template, row):
    return template.format(**row.to_dict())

jobs["prompt_text"] = jobs.apply(lambda r: render(r["template"], r), axis=1)

# Metadata (similar to your R pipeline)
jobs["run_id"] = str(uuid.uuid4())
jobs["model"] = "gemini-3-flash-preview"
jobs["temperature"] = 0

# Stable-ish job id (you can tweak)
jobs["job_id"] = (
    jobs["run_id"] + "::" +
    jobs["intent_label"].astype(str) + "::" +
    jobs.index.astype(str)
)

jobs.head()

import time
import json
import pandas as pd
from pathlib import Path

# Output files
out_csv = Path("results_minimal.csv")
out_json = Path("responses_raw.jsonl")

# Take ONLY the next 15 jobs jobs
test_jobs = jobs.iloc[5:10].copy()

results = []

for _, row in test_jobs.iterrows():
    time.sleep(0.25)  # gentle pacing

    try:
        response = model.generate_content(
            row["prompt_text"],
            generation_config={"temperature": row["temperature"]}
        )

        # Save raw response (JSONL)
        with open(out_json, "a", encoding="utf-8") as f:
            json.dump(response.to_dict(), f)
            f.write("\n")

        response_text = getattr(response, "text", None)

        record = {
            "job_id": row["job_id"],
            "product_id": row["product_id"],
            "domain": row.get("domain"),
            "product_name": row["product_name"],
            "prompt_type": row["prompt_type"],
            "intent_label": row["intent_label"],
            "run_id": row["run_id"],
            "model": row["model"],
            "temperature": row["temperature"],
            "prompt_text": row["prompt_text"],
            "timestamp_utc": pd.Timestamp.utcnow().isoformat(),
            "response_text": response_text,
            "error": None
        }

    except Exception as e:
        record = {
            "job_id": row["job_id"],
            "product_id": row["product_id"],
            "domain": row.get("domain"),
            "product_name": row["product_name"],
            "prompt_type": row["prompt_type"],
            "intent_label": row["intent_label"],
            "run_id": row["run_id"],
            "model": row["model"],
            "temperature": row["temperature"],
            "prompt_text": row["prompt_text"],
            "timestamp_utc": pd.Timestamp.utcnow().isoformat(),
            "response_text": None,
            "error": str(e)
        }

    results.append(record)

    # Append immediately (crash-safe)
    pd.DataFrame([record]).to_csv(
        out_csv,
        mode="a",
        header=not out_csv.exists(),
        index=False
    )

print("✅ Done.")

pd.read_csv("results_minimal.csv").tail(5)

pd.set_option("display.max_colwidth", None)