# -*- coding: utf-8 -*-
"""BVDS_Anthropic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e1gt8pa9nZS5jHTsT_D2DaigKGJyrGHG
"""

import time
import json
import pandas as pd
from pathlib import Path

import google.generativeai as genai

def gemini_call(prompt_text, model, temperature=0):
    response = model.generate_content(
        prompt_text,
        generation_config={
            "temperature": temperature
        }
    )
    return response


# 1) Products (base rows)
products = pd.read_csv("/content/products.csv")

print(products.shape)
products.head()

prompt_variations = [
    {"prompt_type": "intent", "intent_label": "recommend", "template": "Recommend a {product_name}. At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "best_affordable", "template": "Best affordable {product_name}. At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "best_quality", "template": "The best quality {product_name}.At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "most_popular", "template": "Most popular {product_name}.At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."},
    {"prompt_type": "intent", "intent_label": "best_brands_uk", "template": "What are the best brands for {product_name} currently available in the UK? At the very end of your answer, add: BRANDS: [brand1, brand2, ...]\n"
          "Include ONLY manufacturer/company brands you mentioned. No models. No retailers."}
]

import pandas as pd
import uuid

subs = pd.DataFrame(prompt_variations)

# Cross join
products["_tmp"] = 1
subs["_tmp"] = 1
jobs = products.merge(subs, on="_tmp").drop(columns=["_tmp"])
products.drop(columns=["_tmp"], inplace=True)
subs.drop(columns=["_tmp"], inplace=True)

# Render prompt_text
def render(template, row):
    return template.format(**row.to_dict())

jobs["prompt_text"] = jobs.apply(lambda r: render(r["template"], r), axis=1)

# Metadata (similar to your R pipeline)
jobs["run_id"] = str(uuid.uuid4())
jobs["model"] = "gemini-3-flash-preview"
jobs["temperature"] = 0

# Stable-ish job id (you can tweak)
jobs["job_id"] = (
    jobs["run_id"] + "::" +
    jobs["intent_label"].astype(str) + "::" +
    jobs.index.astype(str)
)

jobs.head()

import time
import json
import pandas as pd
from pathlib import Path
from openai import OpenAI

# Initialize client
client = OpenAI(api_key="Instert API Key Here")

# Output files
out_csv = Path("results_minimal.csv")
out_json = Path("responses_raw.jsonl")

# THESE IS WHERE YOU MAKE THE CHANGES FOR THE DIFFERENT PRODUCTS
test_jobs = jobs.iloc[0:3].copy()

results = []

for _, row in test_jobs.iterrows():
    time.sleep(0.25)  # gentle pacing

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",  # you can swap dynamically if needed
            messages=[
                {"role": "user", "content": row["prompt_text"]}
            ],
            temperature=row["temperature"]
        )

        # Extract text
        response_text = response.choices[0].message.content

        # Save raw response (JSONL)
        with open(out_json, "a", encoding="utf-8") as f:
            json.dump(response.model_dump(), f)
            f.write("\n")

        record = {
            "job_id": row["job_id"],
            "product_id": row["product_id"],
            "domain": row.get("domain"),
            "product_name": row["product_name"],
            "prompt_type": row["prompt_type"],
            "intent_label": row["intent_label"],
            "run_id": row["run_id"],
            "model": "gpt-4o-mini",
            "temperature": row["temperature"],
            "prompt_text": row["prompt_text"],
            "timestamp_utc": pd.Timestamp.utcnow().isoformat(),
            "response_text": response_text,
            "error": None
        }

    except Exception as e:
        record = {
            "job_id": row["job_id"],
            "product_id": row["product_id"],
            "domain": row.get("domain"),
            "product_name": row["product_name"],
            "prompt_type": row["prompt_type"],
            "intent_label": row["intent_label"],
            "run_id": row["run_id"],
            "model": "gpt-4o-mini",
            "temperature": row["temperature"],
            "prompt_text": row["prompt_text"],
            "timestamp_utc": pd.Timestamp.utcnow().isoformat(),
            "response_text": None,
            "error": str(e)
        }

    results.append(record)

    # Append immediately (crash-safe)
    pd.DataFrame([record]).to_csv(
        out_csv,
        mode="a",
        header=not out_csv.exists(),
        index=False
    )

print("✅ Done.")

pd.read_csv("results_minimal.csv").tail(3)



pd.set_option("display.max_colwidth", None)