# -*- coding: utf-8 -*-
"""ML on BVDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A455NLI2enzVsq6tDP035QlFytyLhX7P
"""

import pandas as pd

df = pd.read_csv(csv_file_path)
display(df.head())

# Identify top 50 brands from the entire dataset
brand_counts = collections.Counter(flat_brands)
top_50_brands = [brand for brand, count in brand_counts.most_common(50)]
print(f"Defined top 50 brands: {len(top_50_brands)} brands")

import collections

# Get the set of all unique brands in the dataset for efficient lookup
all_unique_brands_set = set(flat_brands)

# Calculate brand_count (number of brands in response)
df['brand_count'] = df['brand_names'].apply(lambda x: len(x.split(',')) if pd.notna(x) else 0)

# Calculate contains_top_brand using top_50_brands
df['contains_top_brand'] = df['brand_names'].apply(lambda x:
    any(brand.strip() in top_50_brands for brand in x.split(',')) if pd.notna(x) else False
)

print("DataFrame with new features (using top 50 brands):")
display(df.head())



# Function to categorize response length based on brand_count
def categorize_response_length(brand_count):
    if 1 <= brand_count <= 5:
        return 1  # Short
    elif 6 <= brand_count <= 10:
        return 2  # Medium
    elif brand_count >= 11:
        return 3  # Long
    else:
        return None # Or handle as appropriate for other cases

# Apply the function to create the new 'response_length_category' column
df['response_length_category'] = df['brand_count'].apply(categorize_response_length)

print("DataFrame with new 'response_length_category' column:")
display(df.head())

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (70-30 ratio) with stratification on 'domain'
df_train, df_test = train_test_split(df, test_size=0.3, random_state=42, stratify=df['domain'])

print(f"Shape of training set: {df_train.shape}")
print(f"Shape of testing set: {df_test.shape}")

# Verify the 'domain' distribution in both sets
print("\nDomain distribution in training set:")
display(df_train['domain'].value_counts(normalize=True))

print("\nDomain distribution in testing set:")
display(df_test['domain'].value_counts(normalize=True))

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Define features (X) and target (y)
features = ['intent_label', 'domain', 'model']
X_train = df_train[features]
y_train = df_train['response_length_category']

# Handle categorical features using one-hot encoding
X_train_encoded = pd.get_dummies(X_train, columns=features, drop_first=True)

print("Shape of encoded training features:", X_train_encoded.shape)
print("First 5 rows of encoded training features:")
display(X_train_encoded.head())

# Initialize and train a RandomForestClassifier model
model = RandomForestClassifier(random_state=42)
model.fit(X_train_encoded, y_train)

print("\nRandomForestClassifier model trained successfully.")

X_test = df_test[features]
X_test_encoded = pd.get_dummies(X_test, columns=features, drop_first=True)

# Align columns (VERY important)
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)

y_pred = model.predict(X_test_encoded)

from sklearn.metrics import classification_report, accuracy_score

print("Accuracy:", accuracy_score(df_test['response_length_category'], y_pred))
print("\nClassification Report:\n")
print(classification_report(df_test['response_length_category'], y_pred))

import matplotlib.pyplot as plt
importances = model.feature_importances_
feature_names = X_train_encoded.columns

feat_imp = pd.Series(importances, index=feature_names)

# Sort and select top 10 features
top_features = feat_imp.sort_values(ascending=False).head(10)

# Create the plot with improved aesthetics
plt.figure(figsize=(10, 6)) # Increased figure size
top_features.plot(kind='bar', color='skyblue') # Changed color

plt.title("Top 10 Feature Importances for Response Length Prediction", fontsize=14) # More descriptive title
plt.xlabel("Features", fontsize=12) # Add x-axis label
plt.ylabel("Importance Score", fontsize=12) # Add y-axis label
plt.xticks(rotation=45, ha='right') # Rotate labels for better readability
plt.grid(axis='y', linestyle='--', alpha=0.7) # Add a grid
plt.tight_layout() # Adjust layout to prevent labels from being cut off
plt.show()

"""## K-Means Clustering for Response Length Patterns

We will now apply K-means clustering to identify natural groupings in our data based on `brand_count` and the `intent_label`.
This can help us understand if there are inherent patterns related to the length of responses and the user's intent.
"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd

# 1. Select features for clustering
clustering_features = ['brand_count', 'intent_label']
df_clustering = df[clustering_features].copy()

# 2. One-hot encode 'intent_label'
df_clustering = pd.get_dummies(df_clustering, columns=['intent_label'], drop_first=True)

print("Features used for clustering:")
display(df_clustering.head())
print(f"Shape of clustering data: {df_clustering.shape}")

# 3. Scale the features
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_clustering)

# Convert scaled array back to DataFrame for better interpretability (optional, but good for inspection)
df_scaled = pd.DataFrame(df_scaled, columns=df_clustering.columns, index=df_clustering.index)

print("Scaled features head:")
display(df_scaled.head())

# 4. Apply K-means clustering (k=3)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10) # n_init is set to 'auto' by default in newer scikit-learn, but explicit for older versions
df['cluster_label'] = kmeans.fit_predict(df_scaled)

print("K-Means clustering complete. Cluster labels added to the original DataFrame.")
display(df[['brand_count', 'intent_label', 'cluster_label']].head())

"""### Cluster Analysis

Now, let's examine the characteristics of each cluster, particularly focusing on the `brand_count` to map them to 'short', 'medium', and 'long' responses.
"""

# Analyze clusters by brand_count and intent_label
cluster_summary = df.groupby('cluster_label')['brand_count'].agg(['mean', 'median', 'std', 'min', 'max'])
print("\nSummary of brand_count per cluster:")
display(cluster_summary)

# Additionally, let's see the distribution of intent_label within each cluster
print("\nIntent label distribution per cluster:")
cluster_intent_distribution = df.groupby('cluster_label')['intent_label'].value_counts(normalize=True).unstack(fill_value=0)
display(cluster_intent_distribution)

# Map clusters to response length categories based on mean brand_count
# Sort clusters by mean brand_count to identify short, medium, long
sorted_clusters = cluster_summary['mean'].sort_values().index

cluster_mapping = {
    sorted_clusters[0]: 'Short (Cluster ' + str(sorted_clusters[0]) + ')',
    sorted_clusters[1]: 'Medium (Cluster ' + str(sorted_clusters[1]) + ')',
    sorted_clusters[2]: 'Long (Cluster ' + str(sorted_clusters[2]) + ')'
}

print("\nProposed Cluster Mapping:")
for cluster_id, description in cluster_mapping.items():
    print(f"  Cluster {cluster_id}: {description} (Mean brand_count: {cluster_summary.loc[cluster_id, 'mean']:.2f})")

# Assign mapped labels to the DataFrame
df['response_length_cluster'] = df['cluster_label'].map(cluster_mapping)
display(df[['brand_count', 'response_length_category', 'cluster_label', 'response_length_cluster']].sample(5))

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Set a style for better aesthetics
sns.set_style("whitegrid")

# Create a figure with two subplots
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# Plot 1: Violin plot of brand_count distribution for each cluster
sns.violinplot(x='response_length_cluster', y='brand_count', data=df,
               ax=axes[0], palette='viridis', order=df['response_length_cluster'].value_counts().index)
axes[0].set_title('Distribution of Brand Count per Response Length Cluster', fontsize=14)
axes[0].set_xlabel('Response Length Cluster', fontsize=12)
axes[0].set_ylabel('Brand Count', fontsize=12)
axes[0].tick_params(axis='x', rotation=20)
axes[0].grid(axis='y', linestyle='--', alpha=0.7)

# Plot 2: Stacked bar chart of intent_label distribution within each cluster
cluster_intent_distribution_plot = df.groupby('response_length_cluster')['intent_label'].value_counts(normalize=True).unstack(fill_value=0)
cluster_intent_distribution_plot.plot(kind='bar', stacked=True, ax=axes[1], cmap='tab20')
axes[1].set_title('Intent Label Distribution per Response Length Cluster', fontsize=14)
axes[1].set_xlabel('Response Length Cluster', fontsize=12)
axes[1].set_ylabel('Proportion of Intent Labels', fontsize=12)
axes[1].tick_params(axis='x', rotation=20)
axes[1].legend(title='Intent Label', bbox_to_anchor=(1.05, 1), loc='upper left')
axes[1].grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""### Distribution of 'Contains Top Brand'

Let's visualize how many of our responses contain a top 50 brand using a pie chart.
"""

import matplotlib.pyplot as plt

# Calculate value counts
brand_presence_counts = df['contains_top_brand'].value_counts()

# Custom autopct function (this lets you include both label + % inside)
def autopct_format(pct):
    total = brand_presence_counts.sum()
    count = int(pct * total / 100)
    return f'{pct:.1f}%\n({count})'

plt.figure(figsize=(8, 8))
plt.pie(
    brand_presence_counts,
    autopct=lambda pct: f'{pct:.1f}%',
    startangle=90,
    colors=['lightgreen', 'lightcoral'],
    textprops={'fontsize': 12},
    pctdistance=0.7
)

plt.title('Proportion of Responses Containing a Top 50 Brand', fontsize=14)
plt.axis('equal')
plt.show()

