# -*- coding: utf-8 -*-
"""Preprocessing and Visualizing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yx2oNB0pGrNWpIsSSFuGhUUU1uhOGP4t
"""



from google.colab import drive
drive.mount('/content/drive')

"""After mounting, specify the path to your data file. For example, if you have a CSV file named `my_data.csv` in the root of your Drive, you can load it like this:"""

import pandas as pd
brands_data = pd.read_csv('/content/DATA SET BRANDS - Hoja 1.csv')
display(brands_data.head())

import re
import numpy as np

# Function to extract text within square brackets (re-using the previous logic)
def extract_from_response_text(text):
    if isinstance(text, str):
        matches = re.findall(r'\[(.*?)\]', text)
        if matches:
            return ', '.join(matches)
    return None

# Function to conditionally fill brand_names
def fill_missing_brand_names(row):
    # Check if brand_names is None or NaN
    if pd.isna(row['brand_names']):
        return extract_from_response_text(row['response_text'])
    else:
        return row['brand_names']

# Apply the function to the DataFrame
brands_data['brand_names'] = brands_data.apply(fill_missing_brand_names, axis=1)

# Display the first few rows to show the updated 'brand_names' column
display(brands_data.head(5))

import re

# Remove square brackets from the 'brand_names' column
brands_data['brand_names'] = brands_data['brand_names'].astype(str).apply(lambda x: re.sub(r'[\[\]]', '', x))

# Display the first few rows to show the updated 'brand_names' column
display(brands_data.head())

brands_data.to_csv('brands_data_complete.csv', index=False)
print("DataFrame 'brands_data' saved to 'brands_data_complete.csv'")

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Ensure 'brand_names' is string type and handle NaNs or empty strings
brands_data['brand_names_cleaned'] = brands_data['brand_names'].astype(str).apply(lambda x: x.strip())

# Function to count brands, handling multiple brands separated by ', '
# Also handles cases where 'brand_names' might be empty after stripping or just 'nan'
def count_brands(brand_string):
    if brand_string and brand_string != 'nan':
        # Split by ', ' and filter out any empty strings that might result from extra commas
        brands = [b.strip() for b in brand_string.split(', ') if b.strip()]
        return len(brands)
    return 0

# Apply the function to create a new column with the count of brands per row
brands_data['brand_count_per_row'] = brands_data['brand_names_cleaned'].apply(count_brands)

# Calculate the average number of brands per row
average_brands_per_row = brands_data['brand_count_per_row'].mean()

print(f"Average number of brands mentioned per row: {average_brands_per_row:.2f}")

# --- Visualization ---

# 1. Histogram of Brand Counts per Row
plt.figure(figsize=(10, 6))
sns.histplot(brands_data['brand_count_per_row'], bins=range(brands_data['brand_count_per_row'].max() + 2), kde=False, color='skyblue', edgecolor='black')
plt.title('Distribution of Number of Brands Mentioned Per Row')
plt.xlabel('Number of Brands')
plt.ylabel('Number of Rows')
plt.xticks(range(brands_data['brand_count_per_row'].max() + 1))
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# 2. Bar chart for the average
plt.figure(figsize=(6, 4))
sns.barplot(x=['Average Brands'], y=[average_brands_per_row], palette='viridis')
plt.title('Average Number of Brands Mentioned Per Row')
plt.ylabel('Average Count')
plt.ylim(0, brands_data['brand_count_per_row'].max() * 1.1) # Set y-limit dynamically
plt.text(0, average_brands_per_row + 0.1, f'{average_brands_per_row:.2f}', ha='center', va='bottom')
plt.tight_layout()
plt.show()

# Clean up temporary column if not needed further
brands_data.drop(columns=['brand_names_cleaned', 'brand_count_per_row'], inplace=True, errors='ignore')

import matplotlib.pyplot as plt
import seaborn as sns
import re

# Re-add 'brand_names_cleaned' and 'brand_count_per_row' for this analysis if they were dropped
# Ensure 'brand_names' is string type and handle NaNs or empty strings
brands_data['brand_names_cleaned'] = brands_data['brand_names'].astype(str).apply(lambda x: x.strip())

# Function to count brands, handling multiple brands separated by ', '
def count_brands(brand_string):
    if brand_string and brand_string != 'nan':
        brands = [b.strip() for b in brand_string.split(', ') if b.strip()]
        return len(brands)
    return 0

# Apply the function to create a new column with the count of brands per row
brands_data['brand_count_per_row'] = brands_data['brand_names_cleaned'].apply(count_brands)

# Identify common intent prefixes and clean up. Some entries might be full job_ids, so we need to extract the base intent.
# The job_id column has values like '3c9c82a4-8979-4ff6-ae0f-715e1f992e89::recommend::330'
# We want 'recommend' from 'recommend::330'.
# Let's adjust the logic to correctly pull the core intent word from the 'job_id' column.

def extract_core_intent(job_id_string):
    parts = job_id_string.split('::')
    if len(parts) > 1 and parts[1]: # If there's a part after the first '::'
        # Check if the part is a UUID or a direct intent string
        if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
            # If the first part is a UUID, the intent is likely the second part (e.g., 'recommend' from 'uuid::recommend::123')
            return parts[1]
        else:
            # If the first part is not a UUID, the intent is likely the first part (e.g., 'recommend' from 'recommend::123')
            return parts[0]
    elif len(parts) == 1:
        # If no '::', the whole string is the intent (or possibly a job_id without specific intent)
        # If it's a UUID, we can't get an intent, so return 'unknown_intent' or similar.
        if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
            return 'unknown_intent'
        else:
            return parts[0] # Assume it's the intent itself
    return 'unknown_intent' # Fallback for any other cases

brands_data['intent_label'] = brands_data['job_id'].apply(extract_core_intent)


# Calculate the average number of brands per intent_label
average_brands_per_intent = brands_data.groupby('intent_label')['brand_count_per_row'].mean()

# Filter out 'job_id' intent label
average_brands_per_intent = average_brands_per_intent[average_brands_per_intent.index != 'job_id'].sort_values(ascending=False)

print("\nAverage number of brands mentioned per intent label:")
display(average_brands_per_intent)

# --- Visualization ---
plt.figure(figsize=(10, 6))
sns.barplot(x=average_brands_per_intent.index, y=average_brands_per_intent.values, palette='viridis')
plt.title('Average Number of Brands Mentioned Per Intent Label')
plt.xlabel('Intent Label')
plt.ylabel('Average Brand Count')
plt.xticks(rotation=0, ha='center')
plt.tight_layout()
plt.show()

# Clean up the temporary columns again if not needed further
brands_data.drop(columns=['brand_names_cleaned', 'brand_count_per_row', 'intent_label'], inplace=True, errors='ignore')



# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import numpy as np

# Install and import wordcloud
try:
    import wordcloud
except ImportError:
#     %pip install wordcloud
    import wordcloud

# Install and import squarify
try:
    import squarify
except ImportError:
#     %pip install squarify
    import squarify

"""### Filtering out the 'domain: domain' category"""

# Filter out rows where 'domain' column has the value 'domain'
filtered_brands_data = brands_data[brands_data['domain'] != 'domain'].copy()

# Get unique valid domains after filtering
valid_domains = filtered_brands_data['domain'].unique()

print("Valid domains for visualization:", valid_domains)

"""**Reasoning**:
The previous steps created and dropped the `brand_names_cleaned` and `intent_label` columns, and `filtered_brands_data` was created without these columns. To fulfill the subtask requirements, I need to ensure that the `brands_data` DataFrame has these columns correctly populated, then filter it to create `filtered_brands_data`, and finally perform the specified replacement in the `intent_label` column.


"""

import re
import pandas as pd

# 1. Define the `extract_core_intent` function (re-defining for clarity in this block)
def extract_core_intent(job_id_string):
    parts = job_id_string.split('::')
    if len(parts) > 1 and parts[1]: # If there's a part after the first '::'
        # Check if the part is a UUID or a direct intent string
        if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
            # If the first part is a UUID, the intent is likely the second part (e.g., 'recommend' from 'uuid::recommend::123')
            return parts[1]
        else:
            # If the first part is not a UUID, the intent is likely the first part (e.g., 'recommend' from 'recommend::123')
            return parts[0]
    elif len(parts) == 1:
        # If no '::', the whole string is the intent (or possibly a job_id without specific intent)
        # If it's a UUID, we can't get an intent, so return 'unknown_intent' or similar.
        if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
            return 'unknown_intent'
        else:
            return parts[0] # Assume it's the intent itself
    return 'unknown_intent' # Fallback for any other cases

# 2. Create `brand_names_cleaned` column in `brands_data`
brands_data['brand_names_cleaned'] = brands_data['brand_names'].astype(str).apply(lambda x: x.strip())

# 3. Create `intent_label` column in `brands_data`
brands_data['intent_label'] = brands_data['job_id'].apply(extract_core_intent)

# 4. Create `filtered_brands_data` by filtering out rows where 'domain' is 'domain'
filtered_brands_data = brands_data[brands_data['domain'] != 'domain'].copy()

# 5. In `filtered_brands_data`, replace 'job_id' with 'unknown_intent' in the `intent_label` column
# This step accounts for any case where 'job_id' might have been incorrectly assigned as an intent label.
filtered_brands_data['intent_label'] = filtered_brands_data['intent_label'].replace('job_id', 'unknown_intent')

print("Processed `filtered_brands_data` head:")
display(filtered_brands_data.head())

print("\nUnique intent labels in `filtered_brands_data` after processing:")
display(filtered_brands_data['intent_label'].unique())

# 1. Overall most mentioned brands

# Ensure 'brand_names' is treated as string and handle potential NaNs
brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')

# Split the brand_names string into a list of individual brands, then flatten the list
all_brands = brands_data['brand_names'].str.split(', ').explode()

# Clean up any leading/trailing whitespace and remove empty strings
all_brands = all_brands.str.strip().replace('', np.nan).dropna()

# Count the occurrences of each brand
overall_brand_counts = all_brands.value_counts()

print("\nOverall Most Mentioned Brands (Top 10):")
display(overall_brand_counts.head(10))

# 2. Most mentioned brands in each domain

print("\nMost Mentioned Brands Per Domain (Top 10 for each):")

# Get unique domains
domains = brands_data['domain'].unique()

for domain in domains:
    print(f"\n--- Domain: {domain} ---")
    # Filter data for the current domain
    domain_data = brands_data[brands_data['domain'] == domain]

    # Split and clean brand names for this domain
    domain_brands = domain_data['brand_names'].str.split(', ').explode()
    domain_brands = domain_brands.str.strip().replace('', np.nan).dropna()

    # Count the occurrences of each brand in this domain
    if not domain_brands.empty:
        domain_brand_counts = domain_brands.value_counts()
        display(domain_brand_counts.head(10))
    else:
        print("No brand names found for this domain.")

import pandas as pd

# Ensure 'brand_names' is treated as string and handle potential NaNs
brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')

# Explode brand_names to have one brand per row
# Create a temporary column for cleaned brand names to use for counting
brands_data['brand_names_cleaned'] = brands_data['brand_names'].str.split(', ').explode()

# Clean up any leading/trailing whitespace and remove empty strings
brands_data['brand_names_cleaned'] = brands_data['brand_names_cleaned'].str.strip().replace('', pd.NA).dropna()

# Group by domain, model, and the cleaned brand names, then count occurrences
brand_mentions_by_model_domain = brands_data.groupby(['domain', 'model', 'brand_names_cleaned']).size().reset_index(name='mentions')

# Display the results for inspection
display(brand_mentions_by_model_domain.head(20))

"""### Visualizations for Each Domain"""

for domain in valid_domains:
    print(f"\n--- Visualizations for Domain: {domain} ---")

    # Filter data for the current domain
    domain_data = filtered_brands_data[filtered_brands_data['domain'] == domain]

    # Split and clean brand names for this domain
    domain_brands_exploded = domain_data['brand_names'].str.split(', ').explode()
    domain_brands_cleaned = domain_brands_exploded.str.strip().replace('', np.nan).dropna()

    if domain_brands_cleaned.empty:
        print("No brand names found for this domain.")
        continue

    # Count the occurrences of each brand in this domain
    domain_brand_counts = domain_brands_cleaned.value_counts()

    # 1. Horizontal Bar Chart (Top 10 Brands)
    plt.figure(figsize=(10, 6))
    sns.barplot(x=domain_brand_counts.head(10).values, y=domain_brand_counts.head(10).index, palette='viridis')
    plt.title(f'Top 10 Most Mentioned Brands in {domain}')
    plt.xlabel('Number of Mentions')
    plt.ylabel('Brand Name')
    plt.tight_layout()
    plt.show()

    # 2. Pie Chart (Top 5 Brands + Others)
    plt.figure(figsize=(8, 8))
    top_5_brands = domain_brand_counts.head(5)
    other_count = domain_brand_counts.iloc[5:].sum()
    if other_count > 0:
        pie_data = pd.concat([top_5_brands, pd.Series({'Others': other_count})])
    else:
        pie_data = top_5_brands

    plt.pie(pie_data, labels=pie_data.index, autopct='%1.1f%%', startangle=140)
    plt.title(f'Brand Mentions Distribution in {domain}')
    plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
    plt.tight_layout()
    plt.show()

    # 3. Word Cloud
    # Create a single string of all brand names for the word cloud
    all_brands_text = ' '.join(domain_brands_cleaned.tolist())
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_brands_text)
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title(f'Word Cloud of Brand Mentions in {domain}')
    plt.tight_layout()
    plt.show()

    # 4. Treemap (Top N Brands)
    plt.figure(figsize=(10, 6))
    top_brands_for_treemap = domain_brand_counts.head(15) # Show top 15 or so for treemap
    if not top_brands_for_treemap.empty:
        squarify.plot(sizes=top_brands_for_treemap.values, label=top_brands_for_treemap.index, alpha=.8 )
        plt.title(f'Treemap of Top Brands in {domain}')
        plt.axis('off')
        plt.tight_layout()
        plt.show()
    else:
        print("Not enough brands to generate a treemap for this domain.")

"""### Comparing Brand Recommendations Across Models within Each Domain"""

# Ensure 'brand_names' is treated as string and handle potential NaNs
brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')

# Split the brand_names string into a list of individual brands, then flatten the list
all_brands = brands_data['brand_names'].str.split(', ').explode()

# Clean up any leading/trailing whitespace and remove empty strings
all_brands = all_brands.str.strip().replace('', pd.NA).dropna()

# Count the occurrences of each brand
overall_brand_counts = all_brands.value_counts()

print("Overall Brand Mentions Across All Models and Domains:")
display(overall_brand_counts)

print("Brand Mentions by Domain, Model, and Brand:")
display(brand_mentions_by_model_domain)

"""### Comparing Brand Mentions by Model"""

# Filter for the two specific models
comparison_data = brand_mentions_by_model_domain[
    brand_mentions_by_model_domain['model'].isin(['gemini-3-flash-preview', 'gpt-4o-mini'])
].copy()

# Pivot the table to have models as columns and brand_names_cleaned as index
comparison_df = comparison_data.pivot_table(
    index='brand_names_cleaned',
    columns='model',
    values='mentions',
    fill_value=0 # Fill NaN with 0 for brands not mentioned by a model
)

# Rename columns for clarity
comparison_df.columns.name = None
comparison_df = comparison_df.rename(columns={
    'gemini-3-flash-preview': 'gemini-3-flash-preview_count',
    'gpt-4o-mini': 'gpt-4o-mini_count'
})

# Add a column for total mentions for sorting
comparison_df['total_mentions'] = comparison_df['gemini-3-flash-preview_count'] + comparison_df['gpt-4o-mini_count']

# Sort by total mentions in descending order
comparison_df = comparison_df.sort_values(by='total_mentions', ascending=False)

print("Comparison of Brand Mentions by 'gemini-3-flash-preview' vs 'gpt-4o-mini':")
display(comparison_df.head(20))

"""### Comparison of Brand Mentions by Model, Per Domain"""

unique_domains = brands_data['domain'].unique()

for domain in unique_domains:
    if domain == 'domain': # Skip the 'domain' entry if it exists and is invalid
        continue

    print(f"\n--- Comparison for Domain: {domain} ---")

    # Filter data for the current domain and specified models
    domain_comparison_data = brand_mentions_by_model_domain[
        (brand_mentions_by_model_domain['domain'] == domain) &
        (brand_mentions_by_model_domain['model'].isin(['gemini-3-flash-preview', 'gpt-4o-mini']))
    ].copy()

    if domain_comparison_data.empty:
        print(f"No brand mentions found for 'gemini-3-flash-preview' or 'gpt-4o-mini' in the '{domain}' domain.")
        continue

    # Pivot the table to have models as columns and brand_names_cleaned as index
    domain_comparison_df = domain_comparison_data.pivot_table(
        index='brand_names_cleaned',
        columns='model',
        values='mentions',
        fill_value=0
    )

    # Rename columns for clarity
    domain_comparison_df.columns.name = None
    domain_comparison_df = domain_comparison_df.rename(columns={
        'gemini-3-flash-preview': 'gemini-3-flash-preview_count',
        'gpt-4o-mini': 'gpt-4o-mini_count'
    })

    # Add a column for total mentions for sorting
    domain_comparison_df['total_mentions'] = domain_comparison_df['gemini-3-flash-preview_count'] + domain_comparison_df['gpt-4o-mini_count']

    # Sort by total mentions in descending order
    domain_comparison_df = domain_comparison_df.sort_values(by='total_mentions', ascending=False)

    display(domain_comparison_df.head(20))

"""### Visualizing Top 10 Brand Mentions by Model, Per Domain"""

import matplotlib.pyplot as plt
import seaborn as sns

# Ensure 'brand_mentions_by_model_domain' is available
# It was previously created in cell 5d8fa9d2
# Re-creating if necessary to be self-contained for this block
if 'brand_mentions_by_model_domain' not in locals():
    # Ensure 'brand_names' is treated as string and handle potential NaNs
    brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')
    brands_data['brand_names_cleaned'] = brands_data['brand_names'].str.split(', ').explode()
    brands_data['brand_names_cleaned'] = brands_data['brand_names_cleaned'].str.strip().replace('', pd.NA).dropna()
    brand_mentions_by_model_domain = brands_data.groupby(['domain', 'model', 'brand_names_cleaned']).size().reset_index(name='mentions')

# Get unique valid domains (assuming 'valid_domains' is already defined, from cell 2c9a373a)
if 'valid_domains' not in locals():
    filtered_brands_data = brands_data[brands_data['domain'] != 'domain'].copy()
    valid_domains = filtered_brands_data['domain'].unique()

for domain in valid_domains:
    print(f"\n--- Top 10 Brand Comparison for Domain: {domain} ---")

    # Filter data for the current domain and specified models
    domain_model_brands = brand_mentions_by_model_domain[
        (brand_mentions_by_model_domain['domain'] == domain) &
        (brand_mentions_by_model_domain['model'].isin(['gemini-3-flash-preview', 'gpt-4o-mini']))
    ].copy()

    if domain_model_brands.empty:
        print(f"No brand mentions found for 'gemini-3-flash-preview' or 'gpt-4o-mini' in the '{domain}' domain.")
        continue

    # Calculate total mentions for each brand within this domain for sorting
    domain_brand_totals = domain_model_brands.groupby('brand_names_cleaned')['mentions'].sum().reset_index()
    domain_brand_totals = domain_brand_totals.sort_values(by='mentions', ascending=False)

    # Get the top 10 brands based on total mentions
    top_10_brands = domain_brand_totals['brand_names_cleaned'].head(10).tolist()

    # Filter the original data to include only the top 10 brands
    comparison_df_plot = domain_model_brands[
        domain_model_brands['brand_names_cleaned'].isin(top_10_brands)
    ].copy()

    # Order the brands for consistent plotting
    comparison_df_plot['brand_names_cleaned'] = pd.Categorical(
        comparison_df_plot['brand_names_cleaned'], categories=top_10_brands, ordered=True
    )
    comparison_df_plot = comparison_df_plot.sort_values('brand_names_cleaned')

    plt.figure(figsize=(12, 7))
    sns.barplot(
        data=comparison_df_plot,
        x='brand_names_cleaned',
        y='mentions',
        hue='model',
        palette='deep'
    )
    plt.title(f'Top 10 Most Mentioned Brands in {domain} by Model')
    plt.xlabel('Brand Name')
    plt.ylabel('Number of Mentions')
    plt.xticks(rotation=45, ha='right')
    plt.legend(title='Model')
    plt.tight_layout()
    plt.show()

"""### Visualizing Top 20 Overall Brand Mentions by Model (Not Divided by Domain)"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure 'brand_mentions_by_model_domain' is available
# Re-creating if necessary to be self-contained for this block
if 'brand_mentions_by_model_domain' not in locals():
    brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')
    brands_data['brand_names_cleaned'] = brands_data['brand_names'].str.split(', ').explode()
    brands_data['brand_names_cleaned'] = brands_data['brand_names_cleaned'].str.strip().replace('', pd.NA).dropna()
    brand_mentions_by_model_domain = brands_data.groupby(['domain', 'model', 'brand_names_cleaned']).size().reset_index(name='mentions')

# Filter for the two specific models first across all domains
overall_model_brands = brand_mentions_by_model_domain[
    brand_mentions_by_model_domain['model'].isin(['gemini-3-flash-preview', 'gpt-4o-mini'])
].copy()

# Aggregate mentions by brand and model across all domains
aggregated_brand_mentions = overall_model_brands.groupby(['model', 'brand_names_cleaned'])['mentions'].sum().reset_index()

# Calculate total mentions for each brand across both models for sorting
total_mentions_per_brand = aggregated_brand_mentions.groupby('brand_names_cleaned')['mentions'].sum().reset_index()
total_mentions_per_brand = total_mentions_per_brand.sort_values(by='mentions', ascending=False)

# Get the top 20 brands based on overall total mentions
top_20_overall_brands = total_mentions_per_brand['brand_names_cleaned'].head(20).tolist()

# Filter the aggregated data to include only the top 20 brands
plot_data = aggregated_brand_mentions[
    aggregated_brand_mentions['brand_names_cleaned'].isin(top_20_overall_brands)
].copy()

# Order the brands for consistent plotting
plot_data['brand_names_cleaned'] = pd.Categorical(
    plot_data['brand_names_cleaned'], categories=top_20_overall_brands, ordered=True
)
plot_data = plot_data.sort_values('brand_names_cleaned')

# Create the grouped bar chart
plt.figure(figsize=(15, 8))
sns.barplot(
    data=plot_data,
    x='brand_names_cleaned',
    y='mentions',
    hue='model',
    palette='deep'
)
plt.title('Top 20 Overall Most Mentioned Brands by Model')
plt.xlabel('Brand Name')
plt.ylabel('Number of Mentions')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Model')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import re # Import re for regex operations

# Ensure brand_names is string type and handle NaNs or empty strings before processing
brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')

# Ensure intent_label is present and correctly defined
if 'intent_label' not in brands_data.columns:
    def extract_core_intent(job_id_string):
        if pd.isna(job_id_string): # Handle NaN job_id
            return 'unknown_intent'
        parts = str(job_id_string).split('::') # Ensure job_id_string is str
        if len(parts) > 1 and parts[1]:
            # If the first part is a UUID, the intent is likely the second part
            if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
                return parts[1]
            else:
                return parts[0] # Assume it's the intent itself
        elif len(parts) == 1:
            # If no '::', the whole string is the intent
            if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
                return 'unknown_intent'
            else:
                return parts[0]
        return 'unknown_intent' # Fallback for any other cases
    brands_data['intent_label'] = brands_data['job_id'].apply(extract_core_intent)

# Filter data for the 'best_affordable' intent type
affordable_brands_data = brands_data[brands_data['intent_label'] == 'best_affordable'].copy()

# Explode the brand_names to get individual brands and clean up
# Use assign().explode() for safer DataFrame explosion, creating 'brand_names_cleaned' directly
affordable_brands_data = affordable_brands_data.assign(
    brand_names_cleaned=affordable_brands_data['brand_names'].str.split(', ')
).explode('brand_names_cleaned')

# Clean up the brand_names_cleaned column
affordable_brands_data['brand_names_cleaned'] = affordable_brands_data['brand_names_cleaned'].str.strip().replace('', pd.NA)

# Drop rows where brand_names_cleaned might be NaN after cleaning (e.g., from empty strings)
affordable_brands_data.dropna(subset=['brand_names_cleaned'], inplace=True)

# Filter for the two specific models
comparison_models_affordable = affordable_brands_data[
    affordable_brands_data['model'].isin(['gemini-3-flash-preview', 'gpt-4o-mini'])
].copy() # Use .copy() to avoid SettingWithCopyWarning

# Aggregate mentions by brand and model
aggregated_affordable_mentions = comparison_models_affordable.groupby(['model', 'brand_names_cleaned']).size().reset_index(name='mentions')

# Calculate total mentions for each brand across both models for sorting
total_mentions_affordable_brand = aggregated_affordable_mentions.groupby('brand_names_cleaned')['mentions'].sum().reset_index()
total_mentions_affordable_brand = total_mentions_affordable_brand.sort_values(by='mentions', ascending=False)

# Get the top N brands based on overall total mentions for this intent
# Let's pick top 15 for a good overview
top_n_affordable_brands = total_mentions_affordable_brand['brand_names_cleaned'].head(15).tolist()

# Filter the aggregated data to include only these top brands
plot_data_affordable = aggregated_affordable_mentions[
    aggregated_affordable_mentions['brand_names_cleaned'].isin(top_n_affordable_brands)
].copy() # Use .copy() to avoid SettingWithCopyWarning

# Order the brands for consistent plotting
plot_data_affordable['brand_names_cleaned'] = pd.Categorical(
    plot_data_affordable['brand_names_cleaned'], categories=top_n_affordable_brands, ordered=True
)
plot_data_affordable = plot_data_affordable.sort_values('brand_names_cleaned')

# Create the grouped bar chart
plt.figure(figsize=(15, 8))
sns.barplot(
    data=plot_data_affordable,
    x='brand_names_cleaned',
    y='mentions',
    hue='model',
    palette='deep'
)
plt.title('Top 15 Most Mentioned Brands for "best_affordable" Prompt by Model')
plt.xlabel('Brand Name')
plt.ylabel('Number of Mentions')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Model')
plt.tight_layout()
plt.show()

"""### Comparing Brand Mentions by Model for Specific Intent Types"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import re

# Ensure brand_names is string type and handle NaNs or empty strings before processing
brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')

# Ensure intent_label is present and correctly defined (re-added for self-contained execution)
if 'intent_label' not in brands_data.columns:
    def extract_core_intent(job_id_string):
        if pd.isna(job_id_string):
            return 'unknown_intent'
        parts = str(job_id_string).split('::')
        if len(parts) > 1 and parts[1]:
            if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
                return parts[1]
            else:
                return parts[0]
        elif len(parts) == 1:
            if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
                return 'unknown_intent'
            else:
                return parts[0]
        return 'unknown_intent'
    brands_data['intent_label'] = brands_data['job_id'].apply(extract_core_intent)

# Define the list of intent labels to compare
comparison_intent_labels = ['best_affordable', 'recommend', 'most_popular', 'best_quality', 'best_brands_uk']

for intent in comparison_intent_labels:
    print(f"\n--- Visualizing Brand Mentions for Intent: {intent} ---")

    # Filter data for the current intent type
    intent_filtered_data = brands_data[brands_data['intent_label'] == intent].copy()

    # Explode the brand_names to get individual brands and clean up
    intent_filtered_data = intent_filtered_data.assign(
        brand_names_cleaned=intent_filtered_data['brand_names'].str.split(', ')
    ).explode('brand_names_cleaned')

    # Clean up the brand_names_cleaned column
    intent_filtered_data['brand_names_cleaned'] = intent_filtered_data['brand_names_cleaned'].str.strip().replace('', pd.NA)

    # Drop rows where brand_names_cleaned might be NaN after cleaning
    intent_filtered_data.dropna(subset=['brand_names_cleaned'], inplace=True)

    # Filter for the two specific models
    comparison_models_intent = intent_filtered_data[
        intent_filtered_data['model'].isin(['gemini-3-flash-preview', 'gpt-4o-mini'])
    ].copy()

    if comparison_models_intent.empty:
        print(f"No brand mentions found for 'gemini-3-flash-preview' or 'gpt-4o-mini' for intent '{intent}'.")
        continue

    # Aggregate mentions by brand and model
    aggregated_intent_mentions = comparison_models_intent.groupby(['model', 'brand_names_cleaned']).size().reset_index(name='mentions')

    # Calculate total mentions for each brand across both models for sorting
    total_mentions_intent_brand = aggregated_intent_mentions.groupby('brand_names_cleaned')['mentions'].sum().reset_index()
    total_mentions_intent_brand = total_mentions_intent_brand.sort_values(by='mentions', ascending=False)

    # Get the top 15 brands based on overall total mentions for this intent
    top_n_intent_brands = total_mentions_intent_brand['brand_names_cleaned'].head(15).tolist()

    # Filter the aggregated data to include only these top brands
    plot_data_intent = aggregated_intent_mentions[
        aggregated_intent_mentions['brand_names_cleaned'].isin(top_n_intent_brands)
    ].copy()

    # Order the brands for consistent plotting
    plot_data_intent['brand_names_cleaned'] = pd.Categorical(
        plot_data_intent['brand_names_cleaned'], categories=top_n_intent_brands, ordered=True
    )
    plot_data_intent = plot_data_intent.sort_values('brand_names_cleaned')

    # Create the grouped bar chart
    plt.figure(figsize=(15, 8))
    sns.barplot(
        data=plot_data_intent,
        x='brand_names_cleaned',
        y='mentions',
        hue='model',
        palette='deep'
    )
    plt.title(f'Top 15 Most Mentioned Brands for "{intent}" Prompt by Model')
    plt.xlabel('Brand Name')
    plt.ylabel('Number of Mentions')
    plt.xticks(rotation=45, ha='right')
    plt.legend(title='Model')
    plt.tight_layout()
    plt.show()

"""### Stacked Bar Chart: Brand Mentions per Intent Type"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import re

# Ensure brand_names is string type and handle NaNs or empty strings before processing
brands_data['brand_names'] = brands_data['brand_names'].astype(str).replace('nan', '')

# Ensure intent_label is present and correctly defined
if 'intent_label' not in brands_data.columns:
    def extract_core_intent(job_id_string):
        if pd.isna(job_id_string):
            return 'unknown_intent'
        parts = str(job_id_string).split('::')
        if len(parts) > 1 and parts[1]:
            if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
                return parts[1]
            else:
                return parts[0]
        elif len(parts) == 1:
            if re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', parts[0]):
                return 'unknown_intent'
            else:
                return parts[0]
        return 'unknown_intent'
    brands_data['intent_label'] = brands_data['job_id'].apply(extract_core_intent)

# Define the list of intent labels to compare
comparison_intent_labels = ['best_affordable', 'recommend', 'most_popular', 'best_quality', 'best_brands_uk']

# Filter data for the specified intent types
filtered_data_for_stack = brands_data[
    brands_data['intent_label'].isin(comparison_intent_labels)
].copy()

# Explode the brand_names to get individual brands and clean up
filtered_data_for_stack = filtered_data_for_stack.assign(
    brand_names_cleaned=filtered_data_for_stack['brand_names'].str.split(', ')
).explode('brand_names_cleaned')

# Clean up the brand_names_cleaned column
filtered_data_for_stack['brand_names_cleaned'] = filtered_data_for_stack['brand_names_cleaned'].str.strip().replace('', pd.NA)

# Drop rows where brand_names_cleaned might be NaN after cleaning
filtered_data_for_stack.dropna(subset=['brand_names_cleaned'], inplace=True)

# Aggregate mentions by intent_label and brand_names_cleaned
aggregated_mentions = filtered_data_for_stack.groupby(['intent_label', 'brand_names_cleaned']).size().reset_index(name='mentions')

# Calculate total mentions for each brand across all selected intents to identify top brands
total_mentions_per_brand_overall = aggregated_mentions.groupby('brand_names_cleaned')['mentions'].sum().reset_index()
top_n_overall_brands = total_mentions_per_brand_overall.sort_values(by='mentions', ascending=False).head(15)['brand_names_cleaned'].tolist()

# Filter to include only the top N brands (removing 'Other' category)
plot_data_stacked = aggregated_mentions[
    aggregated_mentions['brand_names_cleaned'].isin(top_n_overall_brands)
].copy()

# Pivot the table for stacking
pivoted_data_stacked = plot_data_stacked.pivot_table(
    index='intent_label',
    columns='brand_names_cleaned',
    values='mentions',
    fill_value=0
)

# Sort intents by their total mentions for better visualization if desired
pivoted_data_stacked['total'] = pivoted_data_stacked.sum(axis=1)
pivoted_data_stacked = pivoted_data_stacked.sort_values(by='total', ascending=False).drop(columns='total')

# Reorder columns to ensure consistent display (optional, but good practice)
pivoted_data_stacked = pivoted_data_stacked[top_n_overall_brands]

# Plotting the stacked bar chart
plt.figure(figsize=(16, 9))
pivoted_data_stacked.plot(kind='bar', stacked=True, figsize=(16, 9), cmap='tab20')
plt.title('Brand Mentions per Intent Type (Top 15 Overall Brands)')
plt.xlabel('Intent Label')
plt.ylabel('Number of Mentions')
plt.xticks(rotation=0, ha='center')
plt.legend(title='Brand Name', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()